name: Build and deploy Node.js app to Azure Web App - netflixcloneproject

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_ACCESS_TOKEN }}
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Print environment variables
        run: |
          echo "NEXT_PUBLIC_ACCESS_TOKEN=${{ secrets.NEXT_PUBLIC_ACCESS_TOKEN }}"
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present

      - name: 📂 Copy standalone into the root
        run: cp -R ./.next/standalone ./site-deploy

      - name: 📂 Copy static into the .next folder
        run: cp -R ./.next/static ./site-deploy/.next/static

      - name: 📂 Copy Public folder
        run: cp -R ./public ./site-deploy/public

      - name: 📦 Package Next application
        run: |
          cd ./site-deploy
          zip Nextjs-site.zip ./* .next -qr

      - name: 🔍 Diagnostics
        run: |
          ls ./src
          ls ./src/.next
          ls ./site-deploy
          
      - name: ⬆️ Publish Next Application artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nextjs-site
          path: ./site-deploy/Nextjs-site.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    env:
      NEXT_PUBLIC_ACCESS_TOKEN: ${{ secrets.NEXT_PUBLIC_ACCESS_TOKEN }}
      NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
     
    steps:
      - name: 🍏 Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: ⬇️ Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: Nextjs-site
          
      - name: Print environment variables
        run: |
          echo "NEXT_PUBLIC_ACCESS_TOKEN=${{ secrets.NEXT_PUBLIC_ACCESS_TOKEN }}"
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}"


      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'netflixcloneproject'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C8C0724EB2DC4A85B7533FE2098BFC36 }}
          package: .
